/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicMpesaTimeoutRouteImport } from './routes/api/public/mpesa/timeout'
import { Route as ApiPublicMpesaResultRouteImport } from './routes/api/public/mpesa/result'
import { Route as ApiPublicMpesaC2bValidationRouteImport } from './routes/api/public/mpesa/c2b-validation'
import { Route as ApiPublicMpesaC2bConfirmationRouteImport } from './routes/api/public/mpesa/c2b-confirmation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaTimeoutRoute = ApiPublicMpesaTimeoutRouteImport.update({
  id: '/api/public/mpesa/timeout',
  path: '/api/public/mpesa/timeout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaResultRoute = ApiPublicMpesaResultRouteImport.update({
  id: '/api/public/mpesa/result',
  path: '/api/public/mpesa/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaC2bValidationRoute =
  ApiPublicMpesaC2bValidationRouteImport.update({
    id: '/api/public/mpesa/c2b-validation',
    path: '/api/public/mpesa/c2b-validation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpesaC2bConfirmationRoute =
  ApiPublicMpesaC2bConfirmationRouteImport.update({
    id: '/api/public/mpesa/c2b-confirmation',
    path: '/api/public/mpesa/c2b-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/mpesa/c2b-confirmation': typeof ApiPublicMpesaC2bConfirmationRoute
  '/api/public/mpesa/c2b-validation': typeof ApiPublicMpesaC2bValidationRoute
  '/api/public/mpesa/result': typeof ApiPublicMpesaResultRoute
  '/api/public/mpesa/timeout': typeof ApiPublicMpesaTimeoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/mpesa/c2b-confirmation': typeof ApiPublicMpesaC2bConfirmationRoute
  '/api/public/mpesa/c2b-validation': typeof ApiPublicMpesaC2bValidationRoute
  '/api/public/mpesa/result': typeof ApiPublicMpesaResultRoute
  '/api/public/mpesa/timeout': typeof ApiPublicMpesaTimeoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/mpesa/c2b-confirmation': typeof ApiPublicMpesaC2bConfirmationRoute
  '/api/public/mpesa/c2b-validation': typeof ApiPublicMpesaC2bValidationRoute
  '/api/public/mpesa/result': typeof ApiPublicMpesaResultRoute
  '/api/public/mpesa/timeout': typeof ApiPublicMpesaTimeoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/mpesa/c2b-confirmation'
    | '/api/public/mpesa/c2b-validation'
    | '/api/public/mpesa/result'
    | '/api/public/mpesa/timeout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/mpesa/c2b-confirmation'
    | '/api/public/mpesa/c2b-validation'
    | '/api/public/mpesa/result'
    | '/api/public/mpesa/timeout'
  id:
    | '__root__'
    | '/'
    | '/api/public/mpesa/c2b-confirmation'
    | '/api/public/mpesa/c2b-validation'
    | '/api/public/mpesa/result'
    | '/api/public/mpesa/timeout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicMpesaC2bConfirmationRoute: typeof ApiPublicMpesaC2bConfirmationRoute
  ApiPublicMpesaC2bValidationRoute: typeof ApiPublicMpesaC2bValidationRoute
  ApiPublicMpesaResultRoute: typeof ApiPublicMpesaResultRoute
  ApiPublicMpesaTimeoutRoute: typeof ApiPublicMpesaTimeoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/timeout': {
      id: '/api/public/mpesa/timeout'
      path: '/api/public/mpesa/timeout'
      fullPath: '/api/public/mpesa/timeout'
      preLoaderRoute: typeof ApiPublicMpesaTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/result': {
      id: '/api/public/mpesa/result'
      path: '/api/public/mpesa/result'
      fullPath: '/api/public/mpesa/result'
      preLoaderRoute: typeof ApiPublicMpesaResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/c2b-validation': {
      id: '/api/public/mpesa/c2b-validation'
      path: '/api/public/mpesa/c2b-validation'
      fullPath: '/api/public/mpesa/c2b-validation'
      preLoaderRoute: typeof ApiPublicMpesaC2bValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/c2b-confirmation': {
      id: '/api/public/mpesa/c2b-confirmation'
      path: '/api/public/mpesa/c2b-confirmation'
      fullPath: '/api/public/mpesa/c2b-confirmation'
      preLoaderRoute: typeof ApiPublicMpesaC2bConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicMpesaC2bConfirmationRoute: ApiPublicMpesaC2bConfirmationRoute,
  ApiPublicMpesaC2bValidationRoute: ApiPublicMpesaC2bValidationRoute,
  ApiPublicMpesaResultRoute: ApiPublicMpesaResultRoute,
  ApiPublicMpesaTimeoutRoute: ApiPublicMpesaTimeoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
